### PR TITLE
fix: Move `@ember/test-waiters` to peerDependencies

### PR DESCRIPTION
**Pull request by patocallaghan**
Follow up to https://github.com/NullVoxPopuli/ember-resources/pull/407#issuecomment-1051102858

image

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
aw man, I thought this was resolved. 
thanks for opening this PR!

I need to figure out why `@ember/test-waiters` is now missing / unresolveable

**Comment by NullVoxPopuli** [comment]
so this is interesting, and maybe @ef4 knows what's going on (based on [this comment](https://github.com/embroider-build/embroider/pull/1131#issuecomment-1042569721)),

It seems this peerDependency error exists (`@ember/test-waiters` could not be resolved) in yarn monorepos, but not pnpm monorepos [demonstrated here](https://github.com/NullVoxPopuli/ember-resources/pull/413) (embroider scenarios pass in pnpm, but fail in yarn).

My (weak) hypothesis is that this `@ember/test-waiters` issue may only exist in yarn monorepos -- which... still needs to be solved? because my work monorepo is in yarn -- but maybe this is motivation to migrate to pnpm... but then everyone still using yarn1 is out of luck :thinking: 

Is this something we want to absorb in embroider? (or do we tell people to move to pnpm (or maybe yarn3?)

**Comment by ef4** [comment]
> My (weak) hypothesis is that this @ember/test-waiters issue may only exist in yarn monorepos

Yeah, there's no great mystery here. You can inspect the node_modules structure and see what can resolve what.

When using pnpm, you may also need to enable [dependenciesMeta.*.injected](https://pnpm.io/package_json#dependenciesmetainjected) to ensure that your own monorepo packages get the strict handling that ensures they will always get the strictly correct peerDependencies.

Also, I don't recommend using "*" ranges for dependencies within your monorepo. Instead, to guarantee that the dependency will come from the within the monorepo use pnpm's [workspace protocol](https://pnpm.io/workspaces#workspace-protocol-workspace).

> but then everyone still using yarn1 is out of luck

Yarn 1 is totally unsupported by its maintainers, so that was already true. 

> Is this something we want to absorb in embroider?

If we care about compatibility with tools like TypeScript, we literally cannot. We could make imports inside our build mean something different than they mean to node, but typescript won't know that and doesn't allow extension of that.

We have enough legacy behavior like that already, I'm not going to add more.

**Comment by NullVoxPopuli** [comment]
Thanks for the insights and directions! I'm going to discuss with my team migrating to pnpm (we've been wanting to get off yarn1 anyway).

> you may also need to enable [dependenciesMeta.*.injected](https://pnpm.io/package_json#dependenciesmetainjected) to ensure that your own monorepo packages get the strict handling that ensures they will always get the strictly correct peerDependencies

this is good to know! thanks!
(I also really appreciate how detailed the pnpm docs are)

**Pull request merged**
